apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app
      version : v1
  template:
    metadata:
      labels:
        app: iot-app
        version : v1
    spec:
      containers:
      - name: iot-app
        image: wil42/playground:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iot-app
  namespace: dev
spec:
  selector:
    app: iot-dev
  ports:
    - protocol : TCP
      port : 80
      targetPort: 80
      nodePort: 30000
  type: NodePort