apiVersion: v1
kind: Service
metadata:
  name: iot-app
  namespace: dev
spec:
  selector:
    app: iot-app
  ports:
    - protocol: TCP
      port: 85
      targetPort: 80
      nodePort: 30000
  type: NodePort